config/routes.rb
Rails.application.routes.draw do
  get 'images/index'
  get 'preview_image' => 'images#preview'
  get 'validate_balance' => 'wallet_transactions#validate_balance'
  resources :wallet_transactions
  resources :images
  resources :friends do
    member do
      get 'send_request'
      get 'cancel_request'
      get 'confirm_request'
      get 'reject_request'
      get 'friend_list'
    end
  end
  resources :profile do 
    collection do 
      get 'payment'
    end
  end

  resources :payements

  post '/payu_callback'=>'payements#payu_return'

  get '/downvote' => 'likes#downvote'
  root 'home#index'
  get '/referralcode/:code' => 'home#index' ,as: '/referralcode'
  resources :post do 
  	collection do
  		get 'create_comment'
  	end
    member do
      delete 'delete_comment'
    end
  end
  resources :likes ,only: [:index]

  
  # devise_for :users
  devise_for :users, :controllers => {:passwords => "users/passwords",:registrations => "users/registrations",sessions: 'users/sessions'}
  # devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/payements_controller.rb
class PayementsController < ApplicationController

  def index
    @carts = Cart.all
  end

  def show        
    @cart = User.first
  end

  def new
    @cart = Cart.new
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def create
    @cart = Cart.new(params[:cart])
  end


  # def payu_callback
  # end

  def update
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
  end

  def payu_return
    notification = PayuIndia::Notification.new(request.query_string, options = {:key => '4JBWmWpK', :salt => 'Yok72qeGpc', :params => params})
    @user = User.find(notification.invoice) # notification.invoice is order id/cart id which you have submited from payment direction page.
    # @user = User.last
    if notification.acknowledge      
      begin
        if notification.complete?          
          @user.payment_status = 'success'
          @user.payment_at = Time.now
          @transaction = TransactionHistory.create(:total => notification.gross, :card_holder_name => params['name_on_card'], :user_id => notification.invoice)
          redirect_to post_index_url
        else          
          @user.status = "failed"
          render :text => "Transaction Failed! #{notification.message}"
        end
      ensure
        @user.save
      end
    end    
  end
end

app/helpers/payements_helper.rb
module PayementsHelper
end

app/views/payements/show.html.erb
<div id="lp-register">
  <div class="container wrapper">
    <div class="row">
      <div class="col-sm-5">
        <div class="intro-texts">
          <h1 class="text-white">Mera Network</h1>
          <p>Friend Finder is a social network template that can be used to connect people. The template offers Landing pages, News Feed, Image/Video Feed, Chat Box, Timeline and lot more. <br /> <br />Why are you waiting for? Buy it now.</p>
        </div>
      </div>
      <div class="col-sm-6 col-sm-offset-1">
        <div class="reg-form-container"> 
          <!-- Register/Login Tabs-->
          <div class="reg-options">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#payment" data-toggle="tab">Payment</a></li>
            </ul><!--Tabs End-->
          </div>
          <!--Registration Form Contents-->
          <div class="tab-content">
            <div class="tab-pane active subscript" id="register">
              <h3>Subscription Now !!!</h3>
              <p class="text-muted">Be cool and join today. Meet millions</p>
              <!--Register Form-->
              <%= form_for :payements ,url: payements_path ,method: :post do |f| %>
                <div class="row">
                  <div class="form-group col-xs-6">
                    <label for="firstname" class="sr-only">First Name</label>
                    <%= f.text_field :firstname ,class: "form-control input-group-lg",value: "#{current_user.try(:firstname)}" ,readonly: true %>
                  </div>
                  <div class="form-group col-xs-6">
                    <label for="lastname" class="sr-only">Last Name</label>
                    <%= f.text_field :lastname ,class: "form-control input-group-lg",value: "#{current_user.try(:lastname)}"  ,readonly: true  %>
                  </div>
                </div>
                <div class="row">
                  <div class="form-group col-xs-12">
                    <label for="email" class="sr-only">Email</label>
                    <%= f.text_field :email ,class: "form-control input-group-lg",value: "#{current_user.try(:email)}"   ,readonly: true  %>
                  </div>
                </div>
                <div class="row">
                  <div class="form-group col-xs-12">
                    <label  class="sr-only">Phone Number</label>
                    <%= f.text_field :mobile_number ,class: "form-control input-group-lg",value: "#{current_user.try(:mobile_number)} " ,readonly: true %>
                  </div>
                </div>
                <div class="row">
                  <div class="form-group col-xs-12">
                    <input  class="form-control input-group-lg reg_name" type="text"  value="1000" readonly="true" />
                    <p style="font-size:12px; text-align:center;">You will be pay only Rs 1000 Subscription</p>
                  </div>
                </div>                
              <% end %>
              <!--Register Now Form Ends-->
              <div class="row">
                <div class="form-group col-xs-12 text-center">
                 <!-- <button class="btn btn-primary">Pay Now</button> -->
                 <%# payment_form_for_payu 'gtKFFx', 'eCwWELxi',
      :txnid => "abhgy",
      :amount => 12,
      :productinfo => 'Book',
      :firstname => 'abc',
      :email => 'abc@example.com',
      :phone => '1234567890',
      :surl => 'http://localhost:3000/payu_callback',
      :furl => 'http://localhost:3000/payu_callback',
      :html => { :id => 'payment-form' } #%>
      <% payment_form_for_payu '4JBWmWpK','Yok72qeGpc',
                  :txnid => "#{current_user.id}",
                  :amount => 1000,
                  :productinfo => 'UserRegistration',
                  :firstname => "#{current_user.try(:firstname) }",
                  :email => '09artirajora@gmail.com',
                  :phone => '9891155986',
                  :surl => 'http://www.mera.network/payu_callback',
                  :furl => 'http://www.mera.network/payu_callback',
                  :service_provider => 'payu_paisa',
                  :html => { :id => 'payment-form' } %>
                </div>
              </div>
            </div><!--Registration Form Contents Ends-->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>