config/routes.rb
Rails.application.routes.draw do
  get 'images/index'
  get 'preview_image' => 'images#preview'
  get 'validate_balance' => 'wallet_transactions#validate_balance'
  resources :wallet_transactions
  resources :images
  resources :friends do
    member do
      get 'send_request'
      get 'cancel_request'
      get 'confirm_request'
      get 'reject_request'
      get 'friend_list'
    end
  end
  resources :profile do 
    collection do 
      get 'payment'
    end
  end

  resources :payements

  post '/payu_callback'=>'payements#payu_return'

  get '/downvote' => 'likes#downvote'
  root 'home#index'
  get '/referralcode/:code' => 'home#index' ,as: '/referralcode'
  resources :post do 
  	collection do
  		get 'create_comment'
  	end
    member do
      delete 'delete_comment'
    end
  end
  resources :likes ,only: [:index]

  
  # devise_for :users
  devise_for :users, :controllers => {:passwords => "users/passwords",:registrations => "users/registrations",sessions: 'users/sessions'}
  # devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  field :content, type: String , default: ''
  # field :image, type: String , default: ''
  field :video, type: String , default: ''
  field :user_id, type: Integer , default: ''
  belongs_to :user
  has_many :comments ,dependent: :destroy
  has_many :likes ,dependent: :destroy
  has_many :unlikes ,dependent: :destroy
  has_many :images, :dependent => :destroy
  # accepts_nested_attributes_for :images,allow_destroy: true
  
  # mount_uploader :image, AvatarUploader, mount_on: :image

end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user

  def new
  end

  def index
    @new_post = Post.new()
    @posts = current_user.posts.order_by(:created_at.desc)
    @friends = Relationship.friend_list(current_user)
    if params[:post_id]
      @post = Post.find(params[:post_id])
      Comment.create(post_id: @post.id, comment: params[:comment],user_id: current_user.id)
    end
    respond_to do |format|
      format.html{}
      format.js{@post}
    end
  end

  
  def create
    # binding.pry
  	user = current_user
  	post = user.posts.create(content: params[:post][:content])
  	# p"========#{post.inspect}====="
    params[:post][:image].each do |img|
      post.images.create(image: img,user_id: current_user.id)
    end
    flash[:success] = "Post successfully..."
    redirect_to post_index_url
  end

  def comment
    redirect_to post_index_url
  end

  def delete_comment
    comment =  Comment.find(params)
    comment.destroy
    flash[:success] = "Comment delete successfully..."
    redirect_to post_index_url
  end

  def destroy
    post = Post.find(params)
    post.destroy
    flash[:success] = "Post delete successfully..."
    redirect_to post_index_url
  end

  private
  # def post_params 
  #   # binding.pry
  #   params.require(:post).permit(:content, images_attributes: [:id, :image, :_destroy])
  # end

end

app/helpers/post_helper.rb
module PostHelper
end

app/views/post/_comment.html.erb
<% @post.comments.each do |comment| %>
	<div class="post-comment">
	    <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm" />
	    <p><a href="timeline.html" class="profile-link"><%= comment.try(:user).try(:firstname) %> </a>
	    	<!-- <i class="em em-laughing"></i> -->
	    	<%= comment.try(:comment) %> </p> 
	    <% if (current_user == (comment.user || comment.post.user)) %>
	    	<%= link_to "Delete" , delete_comment_post_url(comment.id),method: :delete ,class: "align-delete"%>
	    <% end %>
	</div>
<% end %>

app/views/post/image_cropping.html.erb
<!-- <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script> -->
<script src="/assets/CropBox.js"></script>
<!-- <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script> -->
<script type="text/javascript">
  // $(document).ready(function(){
  //   $('#wallet_form_id').validate({
  //     rules: {
        

  //   "wallet[amount]": {
  //     required: true,
  //     remote: "/validate_balance"
  //   }


  //     },
  //     messages: {
  //       "wallet[amount]": {required: "Please enter amount.",remote: "Balance is insufficient in your wallet."}
  //     },
  //     submitHandler: function(form) {
  //       form.submit();
  //     }
  //   });
  // });
</script>





<div class="container">
    <div class="imageBox">
        <div class="thumbBox"></div>
        <div class="spinner" style="display: none">Loading...</div>
    </div>
    <div class="action">
        <input type="file" id="file" style="float:left; width: 250px">
        <input type="button" id="btnCrop" value="Crop" style="float: right">
        <input type="button" id="btnZoomIn" value="+" style="float: right">
        <input type="button" id="btnZoomOut" value="-" style="float: right">
    </div>
    <div class="cropped">

    </div>
</div>
<script type="text/javascript">
    $(window).load(function() {
        var options =
        {
            thumbBox: '.thumbBox',
            spinner: '.spinner',
            imgSrc: 'avatar.png'
        }
        var cropper;
        $('#file').on('change', function(){
            var reader = new FileReader();
            reader.onload = function(e) {
                options.imgSrc = e.target.result;
                cropper = $('.imageBox').cropbox(options);
            }
            reader.readAsDataURL(this.files[0]);
            this.files = [];
        })
        $('#btnCrop').on('click', function(){
            var img = cropper.getDataURL()
            $('.cropped').append('<img src="'+img+'">');
        })
        $('#btnZoomIn').on('click', function(){
            cropper.zoomIn();
        })
        $('#btnZoomOut').on('click', function(){
            cropper.zoomOut();
        })
    });
</script>

</body>
</html>

<style type="text/css">
  .imageBox
{
    position: relative;
    height: 400px;
    width: 400px;
    border:1px solid #aaa;
    background: #fff;
    overflow: hidden;
    background-repeat: no-repeat;
    cursor:move;
}

.imageBox .thumbBox
{
    position: absolute;
    top: 50%;
    left: 50%;
    width: 200px;
    height: 200px;
    margin-top: -100px;
    margin-left: -100px;
    border: 1px solid rgb(102, 102, 102);
    box-shadow: 0 0 0 1000px rgba(0, 0, 0, 0.5);
    background: none repeat scroll 0% 0% transparent;
}

.imageBox .spinner
{
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    text-align: center;
    line-height: 400px;
    background: rgba(0,0,0,0.7);
}
</style>
<!-- <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script> -->
<script src="/assets/CropBox.js"></script>
<script type="text/javascript">
  /**
 * Created by ezgoing on 14/9/2014.
 */

"use strict";
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        define(['jquery'], factory);
    } else {
        factory(jQuery);
    }
}(function ($) {
    var cropbox = function(options, el){
        var el = el || $(options.imageBox),
            obj =
            {
                state : {},
                ratio : 1,
                options : options,
                imageBox : el,
                thumbBox : el.find(options.thumbBox),
                spinner : el.find(options.spinner),
                image : new Image(),
                getDataURL: function ()
                {
                    var width = this.thumbBox.width(),
                        height = this.thumbBox.height(),
                        canvas = document.createElement("canvas"),
                        dim = el.css('background-position').split(' '),
                        size = el.css('background-size').split(' '),
                        dx = parseInt(dim[0]) - el.width()/2 + width/2,
                        dy = parseInt(dim[1]) - el.height()/2 + height/2,
                        dw = parseInt(size[0]),
                        dh = parseInt(size[1]),
                        sh = parseInt(this.image.height),
                        sw = parseInt(this.image.width);

                    canvas.width = width;
                    canvas.height = height;
                    var context = canvas.getContext("2d");
                    context.drawImage(this.image, 0, 0, sw, sh, dx, dy, dw, dh);
                    var imageData = canvas.toDataURL('image/png');
                    return imageData;
                },
                getBlob: function()
                {
                    var imageData = this.getDataURL();
                    var b64 = imageData.replace('data:image/png;base64,','');
                    var binary = atob(b64);
                    var array = [];
                    for (var i = 0; i < binary.length; i++) {
                        array.push(binary.charCodeAt(i));
                    }
                    return  new Blob([new Uint8Array(array)], {type: 'image/png'});
                },
                zoomIn: function ()
                {
                    this.ratio*=1.1;
                    setBackground();
                },
                zoomOut: function ()
                {
                    this.ratio*=0.9;
                    setBackground();
                }
            },
            setBackground = function()
            {
                var w =  parseInt(obj.image.width)*obj.ratio;
                var h =  parseInt(obj.image.height)*obj.ratio;

                var pw = (el.width() - w) / 2;
                var ph = (el.height() - h) / 2;

                el.css({
                    'background-image': 'url(' + obj.image.src + ')',
                    'background-size': w +'px ' + h + 'px',
                    'background-position': pw + 'px ' + ph + 'px',
                    'background-repeat': 'no-repeat'});
            },
            imgMouseDown = function(e)
            {
                e.stopImmediatePropagation();

                obj.state.dragable = true;
                obj.state.mouseX = e.clientX;
                obj.state.mouseY = e.clientY;
            },
            imgMouseMove = function(e)
            {
                e.stopImmediatePropagation();

                if (obj.state.dragable)
                {
                    var x = e.clientX - obj.state.mouseX;
                    var y = e.clientY - obj.state.mouseY;

                    var bg = el.css('background-position').split(' ');

                    var bgX = x + parseInt(bg[0]);
                    var bgY = y + parseInt(bg[1]);

                    el.css('background-position', bgX +'px ' + bgY + 'px');

                    obj.state.mouseX = e.clientX;
                    obj.state.mouseY = e.clientY;
                }
            },
            imgMouseUp = function(e)
            {
                e.stopImmediatePropagation();
                obj.state.dragable = false;
            },
            zoomImage = function(e)
            {
                e.originalEvent.wheelDelta > 0 || e.originalEvent.detail < 0 ? obj.ratio*=1.1 : obj.ratio*=0.9;
                setBackground();
            }

        obj.spinner.show();
        obj.image.onload = function() {
            obj.spinner.hide();
            setBackground();

            el.bind('mousedown', imgMouseDown);
            el.bind('mousemove', imgMouseMove);
            $(window).bind('mouseup', imgMouseUp);
            el.bind('mousewheel DOMMouseScroll', zoomImage);
        };
        obj.image.src = options.imgSrc;
        el.on('remove', function(){$(window).unbind('mouseup', imgMouseUp)});

        return obj;
    };

    jQuery.fn.cropbox = function(options){
        return new cropbox(options, this);
    };
}));


</script>

app/views/post/index.html.erb
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="/assets/CropBox.js"></script>
<div id="page-contents">
	<div class="container">
		<div class="row">
			<%= render partial: '/home/common/navbar' %>
      <div class="col-md-7">
        <%= render template: 'post/new' %>
        <% @posts.each do |pst| %>
          <div class="post-content">
            <%# pst.images.each do |img| %>
              <%#= image_tag(img.image.url , :alt =>"post-image",class: "img-responsive post-image") %>
            <%# end %>
            <%= image_tag(pst.try(:images).try(:first).try(:image).try(:url) , :alt =>"post-image",class: "img-responsive post-image") %>
            <div class="post-container">
              <% if !pst.try(:user).try(:profile_pic).present? %>
                <img src="http://placehold.it/300x300" alt="user" class="profile-photo-md pull-left" />
              <% else %>
                <%= pst.user.profile_pic  %>
              <% end %>
              <div class="post-detail">
                <div class="user-info">
                  <h5><a href="timeline.html" class="profile-link"><%= "#{pst.user.try(:firstname)}"%>&nbsp;&nbsp;<%= "#{pst.user.try(:lastname)}" %></a>
                    <!-- <span class="following">following</span></h5> -->
                  <p class="text-muted">Published <%= time_ago_in_words(pst.created_at) %> ago</p>
                </div>
                <div class="reaction">
                  <a id='<%= "#{pst.id}" %>' class="btn like"><i class="icon ion-thumbsup"></i>
                  <b id='<%= "like_#{pst.id}" %>'><%= pst.likes.count %></b></a>
                  <a class="btn dislike" id='<%= "downvote_#{pst.id}" %>'><i class="fa fa-thumbs-down"></i>
                    <b id='<%= "postdownvote_#{pst.id}" %>'>

                    <%= pst.unlikes.count %></b></a>
                </div>
                <% if (current_user == pst.user) %>
                  <%= link_to "Delete" , post_url(pst.id),method: :delete %>
                <% end %>
                <div class="line-divider"></div>
                <div class="post-text">
                  <p><%= pst.try(:content) %></p>
                </div>
                <div class="line-divider"></div>
                <div id = '<%= "change_data_#{pst.id}" %>' >
                  <% @post = pst%>
                  <%= render :partial => 'post/comment' , :locals => { :post => @post } %>
                </div>
                <div class="post-comment">
                  <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm " />
                  <input type="text" class="form-control create_post" placeholder="Post a comment" id='<%= "#{pst.id }"%>'>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <!-- Newsfeed Common Side Bar Right
      ================================================= -->
			<!-- <div class="col-md-2 static">
        <div class="suggestions" id="sticky-sidebar">
          <h4 class="grey">Who to Follow</h4>
          <div class="follow-user">
            <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
            <div>
              <h5><a href="timeline.html">Diana Amber</a></h5>
              <a href="#" class="text-green">Add friend</a>
            </div>
          </div>
          <div class="follow-user">
            <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
            <div>
              <h5><a href="timeline.html">Cris Haris</a></h5>
              <a href="#" class="text-green">Add friend</a>
            </div>
          </div>
          <div class="follow-user">
            <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
            <div>
              <h5><a href="timeline.html">Brian Walton</a></h5>
              <a href="#" class="text-green">Add friend</a>
            </div>
          </div>
          <div class="follow-user">
            <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
            <div>
              <h5><a href="timeline.html">Olivia Steward</a></h5>
              <a href="#" class="text-green">Add friend</a>
            </div>
          </div>
          <div class="follow-user">
            <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
            <div>
              <h5><a href="timeline.html">Sophia Page</a></h5>
              <a href="#" class="text-green">Add friend</a>
            </div>
          </div>
        </div>
      </div>
 -->		</div>
	</div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".create_post").on('keyup', function (e) {
      if (e.keyCode == 13) {
        // alert(this.id);
        $.ajax({
          type: "get",
          url: "/post",
          data:{ post_id: this.id,comment: this.value},
          dataType: "script",
          complete: function () { 
            $('.create_post').val('');
          }
        });
      }
    });

    // Like on Post
    $(".like").click(function(){
      var id = this.id;
      var count1 = $("#"+this.id).text();
      var count = parseInt(count1)+1
      $.ajax({
        type: "get",
        url: "/likes",
        data:{ post_id: this.id},
        dataType: "json",
        success:function(data){
          {
            console.log(data.status);
            $("#like_"+id).text(data.count);
            if (data.status == true)
            {
              $('#'+id).addClass('text-green');
            }
            else
            {
              $('#'+id).removeClass('text-green');
            }
          }
        }
      });
    });
    //End
    // DisLike on Post
    $(".dislike").click(function(){
      var id = this.id;
      var count1 = $("#"+this.id).text();
      var count = parseInt(count1)+1
      $.ajax({
        type: "get",
        url: "/downvote",
        data:{ post_id: this.id},
        dataType: "json",
        success:function(data){
          {
            
            $("#post"+id).text(data.count);
            if (data.status == true)
            {
              console.log(data.status+"hello"+data.count+"id"+id);
              $('#'+id).addClass('text-red');
            }
            else
            {
              $('#'+id).removeClass('text-red');
            }
          }
        }
      });
    });
    //End

  });
</script>

<script type="text/javascript">
  function myFunction() {
  /* Get the text field */
  var copyText = document.getElementById("myInput");
  /* Select the text field */
  copyText.select();
  /* Copy the text inside the text field */
  document.execCommand("copy");
  /* Alert the copied text */
  alert("Copied the text: " + copyText.value);
} 
</script>
<!-- <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script> -->
<script type="text/javascript">
  // $(document).ready(function(){
  //   $('#wallet_form_id').validate({
  //     rules: {
        

  //   "wallet[amount]": {
  //     required: true,
  //     remote: "/validate_balance"
  //   }


  //     },
  //     messages: {
  //       "wallet[amount]": {required: "Please enter amount.",remote: "Balance is insufficient in your wallet."}
  //     },
  //     submitHandler: function(form) {
  //       form.submit();
  //     }
  //   });
  // });
</script>

app/views/post/index.js.erb
$('<%= "#change_data_#{@post.id}" %>').html("<%= escape_javascript(render :partial => 'post/comment', :locals => {:post => @post}) %>");

app/views/post/new.html.erb
<div class="create-post">
	<div class="row">
		<%= form_for :post ,url: post_index_url,:html => { :multipart => true },method: :post do |f| %>
			<div class="col-md-8 col-sm-7">
	      <div class="form-group">
	        <img src="http://placehold.it/300x300" alt="" class="profile-photo-md" />
	        <%= f.text_area :content ,class: "form-control" ,placeholder: "Write what you wish",cols: "60", rows: "1"%>
	        <!-- <textarea name="texts" id="exampleTextarea" cols="30" rows="1" class="form-control" placeholder="Write what you wish"></textarea> -->
	      </div>
	    </div>
			<div class="col-md-4 col-sm-5">
	      <div class="tools">
	        <ul class="publishing-tools list-inline">
	         <li><label class="btn-bs-file ion-images" data-toggle="modal" data-target="#myImage"></label></li>
             <li><a href="#"><i class="ion-ios-videocam"></i></a></li>
            <!--  Multipal image model open-->
            <div id="myImage" class="modal myWallet mypost" role="dialog">
              <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="ion-close-round"></i>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="mera-wallate one">
                        <h6>MERA NETWORK UPLOAD PHOTO</h6>
                        <div class="create-post wallets">
                            <div class="form-group">
                                <img src="http://placehold.it/300x300" alt="" class="profile-photo-md">
                                <textarea name="texts" id="exampleTextarea" cols="30" rows="1" class="form-control" placeholder="Write what you wish"></textarea>
                              </div>
                        </div>
                        <div class="upload-img-all">
                            
                            <%#= f.fields_for :images_attributes do |builder| %>

                                <%= f.file_field :image ,class: "uploadimg" ,id: "files" ,multiple: true %>
                              <!-- <input type="file" class="uploadimg" id="files" name="files[]" multiple /> -->
                            <%# end %>
                            <div class="multipal-img"></div>
                        </div>
                        <div class="post-margin">
                            <button class="btn btn-primary">Post</button>
                        </div>
                    </div>
               
                  </div>
                </div>
              </div>
            </div>
            <!--  Multipal image model close -->


	          <!-- <li><label class="btn-bs-file ion-images"> -->
	          	<!-- <%#= f.file_field :image %></label></li> -->
	          <!-- <li><a href="#"><i class="ion-ios-videocam"></i></a></li> -->
	          <!-- <li><a href="#"><i class="ion-map"></i></a></li> -->
	        </ul>
	        <%= f.submit 'Publish' ,class: "btn btn-primary pull-right"%>
	        <!-- <button >Publish</button> -->
	      </div>
	    </div>
	  <% end %>
	</div>
</div>

 <!-- Scripts
    ================================================= -->
    <!-- <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCTMXfmDn0VlqWIyoOxK8997L-amWbUPiQ&callback=initMap"></script> -->
    <!-- <script src="/assets/jquery-3.1.1.min.js"></script> -->
    <!-- <script src="/assets/bootstrap.min.js"></script> -->
    <script src="/assets/jquery.sticky-kit.min.js"></script>
    <script src="/assets/jquery.scrollbar.min.js"></script>
    <script src="/assets/script.js"></script>

<script type="text/javascript">
        $(document).ready(function() {     
        // alert('jiii');    
         if(window.File && window.FileList && window.FileReader) {
         $("#files").on("change",function(e) {
         var files = e.target.files ,
         filesLength = files.length ;
         for (var i = 0; i < filesLength ; i++) {
         var f = files[i]
         var fileReader = new FileReader();
         fileReader.onload = (function(e) {
         var file = e.target;
         $("<img></img>",{
         class : "imageThumb",
         src : e.target.result,
         title : file.name
         }).appendTo(".multipal-img");
         });
         fileReader.readAsDataURL(f);
         }
        });
         } else { alert("Your browser doesn't support to File API") }
        });
    </script>