config/routes.rb
Rails.application.routes.draw do
  get 'images/index'
  get 'preview_image' => 'images#preview'
  get 'validate_balance' => 'wallet_transactions#validate_balance'
  resources :wallet_transactions
  resources :images
  resources :friends do
    member do
      get 'send_request'
      get 'cancel_request'
      get 'confirm_request'
      get 'reject_request'
      get 'friend_list'
    end
  end
  resources :profile do 
    collection do 
      get 'payment'
    end
  end

  resources :payements

  post '/payu_callback'=>'payements#payu_return'

  get '/downvote' => 'likes#downvote'
  root 'home#index'
  get '/referralcode/:code' => 'home#index' ,as: '/referralcode'
  resources :post do 
  	collection do
  		get 'create_comment'
  	end
    member do
      delete 'delete_comment'
    end
  end
  resources :likes ,only: [:index]

  
  # devise_for :users
  devise_for :users, :controllers => {:passwords => "users/passwords",:registrations => "users/registrations",sessions: 'users/sessions'}
  # devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user.present?
      redirect_to post_index_url
  	end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/common/_follow_friends.html.erb
<div class="col-md-2 static">
  <div class="suggestions" id="sticky-sidebar">
    <h4 class="grey">Who to Follow</h4>
    <!-- <div class="follow-user">
      <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
      <div>
        <h5><a href="timeline.html">Diana Amber</a></h5>
        <a href="#" class="text-green">Add friend</a>
      </div>
    </div>
    <div class="follow-user">
      <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
      <div>
        <h5><a href="timeline.html">Cris Haris</a></h5>
        <a href="#" class="text-green">Add friend</a>
      </div>
    </div>
    <div class="follow-user">
      <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
      <div>
        <h5><a href="timeline.html">Brian Walton</a></h5>
        <a href="#" class="text-green">Add friend</a>
      </div>
    </div>
    <div class="follow-user">
      <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
      <div>
        <h5><a href="timeline.html">Olivia Steward</a></h5>
        <a href="#" class="text-green">Add friend</a>
      </div>
    </div>
    <div class="follow-user">
      <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm pull-left" />
      <div>
        <h5><a href="timeline.html">Sophia Page</a></h5>
        <a href="#" class="text-green">Add friend</a>
      </div>
    </div> -->
  </div>
</div>

app/views/home/common/_footer.html.erb
<% if current_user %>
    <footer id="footer">
      <div class="container">
      	<div class="row">
          <div class="footer-wrapper">
            <div class="col-md-12 col-sm-12">
				<div class="logo-ftr text-center">
					<a href="/"><img src="/assets/logo-black.png" alt="" class="footer-logo" /></a>
				</div>              
              <ul class="footer-links text-center">
                <!-- <li><a href="register.html" target="_blank"><i class="fa fa-circle" aria-hidden="true"></i> Signup</a></li> -->
                <!-- <li><a href="register.html" target="_blank"><i class="fa fa-circle" aria-hidden="true"></i> login</a></li> -->
                <li><a href="" target="_blank"><i class="fa fa-circle" aria-hidden="true"></i> About us</a></li>
                <li><a href="" target="_blank"><i class="fa fa-circle" aria-hidden="true"></i> Privacy Policy</a></li>
                <li><a href="" target="_blank"><i class="fa fa-circle" aria-hidden="true"></i> Advertising with us</a></li>
                <li><a href="" target="_blank"><i class="fa fa-circle" aria-hidden="true"></i> Contact us</a></li>
              </ul>
            </div>



          </div>
      	</div>
      </div>
      <div class="copyright">
        <p>Mera Network © 2018. All rights reserved</p>
      </div>
		</footer>
    
    <!--preloader-->
    <div id="spinner-wrapper">
      <div class="spinner"></div>
    </div>
    
    <!-- Scripts
    ================================================= -->
    
    <!-- <script src="/assets/jquery-3.1.1.min.js"></script> -->
    <!-- <script src="/assets/bootstrap.min.js"></script> -->
    <script src="/assets/jquery.sticky-kit.min.js"></script>
    <script src="/assets/jquery.scrollbar.min.js"></script>
    <script src="/assets/script.js"></script>
<% end %>

app/views/home/common/_header.html.erb
<% unless current_user %>
  <header id="header-inverse">
    <nav class="navbar  navbar-fixed-top menu">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if !current_user.present? %>
            <a class="navbar-brand" href="/">
              <img src="/assets/logo.png" alt="logo" />
            </a>
          <% end %>
        </div>
      </div><!-- /.container -->
    </nav>
  </header>
<% else %>
  <header id="header">
    <nav class="navbar navbar-default navbar-fixed-top menu">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="/assets/logo.png" alt="logo" /></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right main-menu">
               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="ion-person-stalker"></i> </a>
                <%= render template: '/friends/request' %>
              </li>
             
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="img-user"><img src="/assets/rkumar.png"/></span> <%= current_user.firstname.camelize %><span style="margin:0 0 0 3px;"> <img src="/assets/down-arrow.png" alt="" /></span></a>
                <ul class="dropdown-menu users-login">
                  <li><a href="/profile/<%= current_user.id %>"><i class="ion-android-person dark-blue"></i> My Profile</a></li>
                  <li><a href="#"><i class="ion-compose pink-color"></i> Edit</a></li>
                  <li><a href="#"><i class="ion-mouse orange-color"></i> Setting</a></li>
                  <li><a href="#"><i class="ion-gear-b light-green"></i> Support</a></li>
                  <li><a href="/users/sign_out" data-method="delete"><i class="ion-unlocked red-color"></i> Logout</a></li>
                </ul>
              </li>
            </ul>
            <%= render template: "/home/common/search"%>
        </div>
      </div>
    </nav>
  </header>
<% end %>

app/views/home/common/_navbar.html.erb
<div class="col-md-3 static">
        <div class="profile-card">
          <img src="http://placehold.it/300x300" alt="user" class="profile-photo" />
          <h5><a href="timeline.html" class="text-white"><%= current_user.try(:firstname) %> <%= current_user.try(:lastname) %></a>
          </h5>
          <a href="/friends/<%= current_user.id %>/friend_list" class="text-white"><i class="ion ion-android-person-add"></i>  <%= @current_user.friends.count %>  Friends</a>
        </div>
        <div class="refferl-code">
          <h4 class="grey">Refer your friend and earn Rs 500 for each Referral <span class="error">*</span></h4>
          <div class="reffrel-main">
            <div class="view-row first">
              <input type="text" value='<%= "http://www.mera.network/referralcode/#{current_user.referral_code}" %>' id="myInput" />
              <span onclick="myFunction()">COPY</span>
              <!-- <span onclick="myFunction()">Copy</span>  -->
            </div>
            <!-- <div class="view-row last">
              <input type="text"/>
              <span>COPY</span>
            </div> -->
          </div>
        </div>
        <!--profile card ends-->
        <ul class="nav-news-feed">
          <!--  Wallet model open-->
          <div id="myWallet" class="modal myWallet" role="dialog">
            <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <i class="ion-close-round"></i>
              </button>
              </div>
              <div class="modal-body">
              <div class="mera-wallate">
                <h4 class="grey">Mera Network Wallet</h4>
                <h5> Available Balance</h5>
                <div class="wallet-amt">
                  <h6>INR <%= current_user.try(:amount) %></h6>
                  <p>Withdrawal Amount</p>
                </div>
                <div class="withdraw-text">
                  <%= form_for :wallet ,url: wallet_transactions_url,method: :post ,html: {id: "wallet_form_id"} do |f| %>
                    <%# if (current_user.try(:amount) > 1999) %>
                      <!-- <input type="text" placeholder="Enter Amount" /> -->
                    <%# else %>
                      <%= f.text_field :amount ,placeholder: "Enter Amount" %>
                      <!-- <input type="text" placeholder="Enter Amount" /> -->
                    <%# end %>
                    <%= f.submit 'WITHDRAWAL', class: "btn btn-block btn-primary" %>
                  <% end %>
                </div>
                <div class="banking-txt">
                  <p><span class="error">*</span> Minimum Withdrawal Amount INR 2000.00</p>
                  <p><span class="error">*</span> Minimum withdrawal will be process 24 Banking Hours</p>
                </div>
              </div>
            
              </div>
            </div>
            </div>
          </div>
          <!--  Wallet model close -->
          <li><i class="ion-ios-download ion-images"></i><div><a href="#" data-toggle="modal" data-target="#myWallet">Wallet</a></div></li>
        <!-- <li><i class="icon ion-ios-paper"></i><div><a href="/images">Images</a></div></li> -->
        <li><i class="icon ion-ios-paper"></i><div><a href="/post">My Newsfeed</a></div></li>
        </ul>
      </div>

app/views/home/common/_publish_post.html.erb
<div class="create-post">
	<div class="row">
		<div class="col-md-7 col-sm-7">
      <div class="form-group">
        <img src="http://placehold.it/300x300" alt="" class="profile-photo-md" />
        <textarea name="texts" id="exampleTextarea" cols="30" rows="1" class="form-control" placeholder="Write what you wish"></textarea>
      </div>
    </div>
		<div class="col-md-5 col-sm-5">
      <div class="tools">
        <ul class="publishing-tools list-inline">
          <li><a href="#"><i class="ion-compose"></i></a></li>
          <li><a href="#"><i class="ion-images"></i></a></li>
          <li><a href="#"><i class="ion-ios-videocam"></i></a></li>
          <li><a href="#"><i class="ion-map"></i></a></li>
        </ul>
        <button class="btn btn-primary pull-right">Publish</button>
      </div>
    </div>
	</div>
</div>

app/views/home/common/search.html.erb
<form class="navbar-form text-center hidden-sm people-search newpeople-search">
  <div class="form-group">
    <i class="icon ion-android-search"></i>
    <input type="text" class="form-control" id="find_friend" placeholder="Search">
  </div>
  <div class="search-ftr" style="display:none;">
    <div class="title-f" id="friend_search">
      <h3>Recent Searches</h3>
      <a href="#"><i class="fa fa-search"></i></a>
    </div>
  </div>
</form>
<script type="text/javascript">
  // #Start Search Friend functionality
    $("#find_friend").keyup(function(){
      $(".search-ftr").show();
      var search = this.value;
      $.ajax({
        type: "get",
        url: "/friends",
        data:{ search: search},
        dataType: "json",
        success:function(data){
          {
            var html = "";
             $.each(data.users,function(i, value ) {
              console.log(value);
              // html += "<a value="+value.id+">"+value.branch_name+"</a>"
              html += "<a href="+"/profile/"+value.id+"><i class='fa fa-search'></i>"+value.firstname+"</a>"
            });           
            $("#friend_search").html(html);
          }                   
        }
      });
    });
  //End
</script>